# Generated by Django 5.1.3 on 2024-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(db_column='first_name', max_length=100, null=True)),
                ('lastName', models.CharField(db_column='last_name', max_length=100, null=True)),
                ('otherName', models.CharField(db_column='other_name', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
