# Generated by Django 5.1.3 on 2024-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(db_column='product_name', max_length=200)),
                ('imageName', models.CharField(db_column='image_name', max_length=500)),
                ('imageId', models.IntegerField(db_column='image_id')),
                ('price', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
