# Generated by Django 5.1.3 on 2024-12-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.CharField(db_column='order_id', max_length=6)),
                ('customerId', models.IntegerField(db_column='customer_id')),
                ('productId', models.IntegerField(db_column='product_id')),
                ('paymentStatus', models.CharField(db_column='payment_status', max_length=200)),
                ('shippingAddress', models.CharField(db_column='shipping_address', max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('postCode', models.CharField(db_column='postcode', max_length=50)),
                ('dateCreate', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(db_column='product_name', max_length=200)),
                ('imageName', models.CharField(db_column='image_name', max_length=500)),
                ('imageId', models.IntegerField(db_column='image_id')),
                ('price', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
